---
title: "SV analysis"
output: md_document
---

# Setup
## Functions
```{r}
library(ggplot2)
library(cowplot)
library(rhdf5)
library(pannagram)
library(igraph)
library(ggnet)
library(network)

```

## Paths
```{r}

s.species = 'b_juncea'
path.sv = '/Volumes/Samsung_T5/vienn/test/b_juncea/'

s.species = 'b_rapa'
path.sv = '/Volumes/Samsung_T5/vienn/test/b_rapa/'

s.species = 'camelina_sativa'
path.sv = '/Volumes/Samsung_T5/vienn/test/camelina_sativa/'

s.species = 'b_nigra'
path.sv = '/Volumes/Samsung_T5/vienn/test/b_nigra/'

s.species = 'cucumber'
path.sv = '/Users/annaigolkina/Library/CloudStorage/OneDrive-Personal/iglab/projects/ufo_proj/07_sv/cucumber/'

s.species = 'auqilegia'
path.sv = '/Users/annaigolkina/Library/CloudStorage/OneDrive-Personal/iglab/projects/ufo_proj/07_sv/auqilegia/'

path.figures = paste(path.sv, 'figures/', sep = '')

if (!dir.exists(path.figures)) {
  dir.create(path.figures)
}

```

## Variables
```{r}
sim.cutoff = 0.85
f.visualise = F
```

## Binning
```{r}

bins <- c(0, 100, 200, 400, 800, 1000, 1500, 3000, 5000, 7000, Inf)
labels <- c("0-100", "100-200", "200-400", "400-800", "800-1000", "1000-1500", "1500-3000", "3000-5000", "5000-7000", "7000+")


color.pal <- c("0-100" = "#1f77b4", "100-200" = "#50B498", "200-400" = "#2ca02c", 
            "400-800" = "#bcbd22", "800-1000" = "#ff7f0e", "1000-1500" = "#d62728", "1500-3000" = "#9467bd",
            "3000-5000" = "#e377c2", "5000-7000" = "#8c564b", "7000+" = "#7f7f7f")


```


# SV-graph
# Reading and constructing
```{r}

res.cover.file = 'seq_sv_big_on_sv_cover.rds'
res.nest = readRDS(paste(path.sv, res.cover.file, sep = ''))
g.content = getGraphFromBlast(res.nest = res.nest, sim.cutoff = sim.cutoff, collapse = F)

```


# Plot simple graph
```{r}
if(f.visualise){
  g <- network(g.content$edges, matrix.type = "edgelist", ignore.eval = FALSE, directed = TRUE)
  b.graph.names = network.vertex.names(g)

  set.seed(239)
  p.refined <- ggnet2(g, label = F, edge.color = "black",
              # node.size = g.nodes.cnt[b.graph.names],
              node.size = 1,
              color = '#468B97',
              arrow.gap = 0.01, arrow.size = 2,
              # color = g.nodes.fam[b.graph.names],
              # palette = fam.palette,
              # mode = "kamadakawai"
              )
  
  p.refined
}

```


### Remove one the biggest component and some the smallest
```{r}
g.comp <- getGraphComponents(g.content$edges)
memb.comp = g.comp$membership

id.big = which.max(g.comp$csize)
sv.name.big = names(g.comp$membership)[g.comp$membership == id.big]

g.content$edges.small = g.content$edges[!(g.content$edges[,1] %in% sv.name.big),]

idx.moderate = which(g.comp$csize >= 4)
sv.name.moderate = names(g.comp$membership)[g.comp$membership %in% idx.moderate]

g.content$edges.small = g.content$edges.small[(g.content$edges.small[,1] %in% sv.name.moderate),]
```

# Only the inresesting length range
```{r}

len.max = 400
len.min = 200

sv.len.tmp = as.numeric(sapply(names(g.comp$membership), function(s) strsplit(s, '\\|')[[1]][2]))
tmp = tapply(sv.len.tmp, g.comp$membership, function(a) sum((a <= len.min) | (a >= len.max)))
comp.remove = tmp[tmp != 0]

comp.get = setdiff(1:g.comp$no, as.numeric(names(comp.remove)))

sv.get = names(g.comp$membership)[g.comp$membership %in% comp.get]
g.content$edges.small = g.content$edges.small[(g.content$edges.small[,1] %in% sv.get),]

dim(g.content$edges.small)

```

#### Plot small component
```{r}

g.sm <- network(g.content$edges.small, matrix.type = "edgelist", ignore.eval = FALSE, directed = TRUE)
b.graph.names = network.vertex.names(g.sm)
set.seed(239)
p.sm <- ggnet2(g.sm, label = F, edge.color = "black",
            # node.size = g.nodes.cnt[b.graph.names],
            node.size = 1,
            color = '#468B97',
            arrow.gap = 0.01, arrow.size = 2,
            # color = g.nodes.fam[b.graph.names],
            # palette = fam.palette,
            # mode = "kamadakawai"
            )

p.sm

```

### With labels
```{r}

g.names = network.vertex.names(g.sm)

g.comp <- getGraphComponents(g.content$edges.small)
memb.comp = g.comp$membership

g.label = rep('', length(g.names))
names(g.label) = g.names
g.label[names(memb.comp)] = as.character(memb.comp)
g.label[duplicated(g.label)] = ''

g.sm %v% "labels" = g.label

g.names.len = as.numeric(sapply(g.names, function(s) strsplit(s, '\\|')[[1]][2]))
g.names.len.bin <- as.character(cut(g.names.len, breaks = bins, right = FALSE, labels = labels))
g.sm %v% "colors" = as.character(g.names.len.bin)


p <- ggnet2(g.sm, label = 'labels', edge.color = "grey70", 
            # node.size = g.content$nodes.traits[g.part.sub.big.names,]$cnt, 
            # color = g.content$nodes.traits[g.part.sub.big.names,]$type,
            # mode = 'kamadakawai',
            node.size = 1,
            color = 'colors',
            palette = color.pal
            ) + 
  # theme(legend.position = "none") +
  guides(size = F)
p


png(paste0(path.figures, 'graph_small_', s.species,'.png', sep = ''), width = 6, height = 6, units = "in", res = 300)
print(p)    
dev.off()

```


# Get sequences from every component
## Read sequence
```{r}
seqs = readFasta(paste0(path.sv, 'seq_sv_big.fasta'))
```

## Save all components
```{r}

comp.used = unique(g.comp$membership[b.graph.names])

s.ufo = c()

for(i.comp in comp.used){
  pokaz(i.comp)
  i.seq = which(memb.comp == i.comp)
  names.comp = names(memb.comp)[i.seq]
  s = seqs[names.comp[1]]

  s.ufo[paste0('comp', i.comp)] = s
}

names(s.ufo) = paste0(s.species, '|', names(s.ufo))

writeFasta(s.ufo, paste0(path.sv, 'ufo_',s.species,'.fasta'))


```

```{r}
stop()
```



```{r}
x = read.table('/Volumes/Samsung_T5/vienn/test/ufo/tmp.txt', stringsAsFactors = F)
x$s1 = sapply(x$V1, function(s) strsplit(s, '\\|')[[1]][1])
x$s2 = sapply(x$V10, function(s) strsplit(s, '\\|')[[1]][1])

x = x[x$s1 != x$s2,]

x = x[x$V7 > 200,]


p.list = list()
for(i in 1:nrow(x)){
  pokaz(i)
  s = x$V8[i]
  p = dotplot.s(s, s, 15, 8)  
  p.list[[i]] = p
}

library(gridExtra)
grid.arrange(grobs = p.list, nrow = 7)


png(paste0(path.figures, 'graph_small_', s.species,'.png', sep = ''), width = 16, height = 16, units = "in", res = 300)
grid.arrange(grobs = p.list, nrow = 7)
dev.off()



i = 15
p.list[[i]]
s = x$V8[i]
dotplot.s(s, s, 15, 13)  

```


### Separate components
```{r}
i.comp = 5
i.seq = which(memb.comp == i.comp)

names.comp = names(memb.comp)[i.seq]

s = seqs[names.comp[2]]
dotself.s(s, 15, 12)

dotself.s(s, 15, 10)

dotplot.s(s, s, 15, 8)

```


```{r}

s1 = seqs[names.comp[1]]
s2 = seqs[names.comp[2]]

g.content$edges.small[g.content$edges.small[,1] %in% c(names.comp[1], names.comp[2]),]

dotplot.s(s1, s2, 15, 13)

```




```{r}
g.comp$membership[g.comp$membership == 1]

seqs.target = seqs[names(memb.comp)]

writeFasta(seqs.target, paste0(path.sv, 'seq_sv_big_target.fasta'))
```


# ORF
```{r}

orf.res = orfFinder(s)

orfplot(orf.res$pos)

head(orf.res$orf)

orf.res$orf[1]


```
