name: pannagram
channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base==4.3.3
  - r-foreach==1.5.2
  - r-crayon==1.5.3
  - r-optparse==1.7.5
  - r-doparallel==1.0.17
  - r-ggplot2==3.5.1
  - r-stringi==1.8.4
  - bioconductor-rhdf5==2.46.1
  - bioconductor-muscle==3.44.0
  
  - blast==2.5.0
  - mafft==7.526