name: pannagram
channels:
  - bioconda
  - defaults
dependencies:
  - "r-base>=4.2.0,<5"
  - "r-foreach>=1.5.2,<2"
  - "r-crayon>=1.5.1,<2"
  - "r-optparse>=1.7.1,<2"
  - "r-doparallel>=1.0.17,<2"
  - "r-ggplot2>=3.3.6,<4"
  
  - "blast>=2.12.0,<3"
  - "mafft>=7.505,<8"