library(testthat)

test_file("tests/testthat/readFastaMy.R")
test_file("tests/testthat/writeFastaMy.R")
test_file("tests/testthat/seq2int.R")
test_file("tests/testthat/nt2seq.R")
test_file("tests/testthat/splitSeq.R")
test_file("tests/testthat/aln2mx.R")
test_file("tests/testthat/mx2aln.R")
test_file("tests/testthat/mx2seq.R")