---
title: "R Notebook"
output: html_notebook
---

```{r}
library(ggplot2)
if (!require(igraph)) install.packages("igraph")

library(igraph)
y.init = y
```


```{r}
plotSynDot(y.init)
```



```{r}
y = y.init
df = transform_positions(y)
plotSynDot(df)

```


```{r}
b = y.init[,2:5]

x.min = min(c(b$V2, b$V3))
x.max = max(c(b$V2, b$V3))
y.min = min(c(b$V4, b$V5))
y.max = max(c(b$V4, b$V5))

b = rbind(c(x.min, x.min, y.min, y.min),
          b,
          c(x.max, x.max, y.max, y.max))


plotSynDot(b)

```

```{r}
b = b[order(b$V2),]
n = nrow(b)
dx = matrix(0, nrow = n, ncol = n)
dy = matrix(0, nrow = n, ncol = n)

b$x = (b$V2 + b$V3) / 2
b$y = (b$V4 + b$V5) / 2
b$xlen = abs(b$V3 - b$V2)
b$ylen = abs(b$V5 - b$V4)
b$xd = b$xlen / 2
b$yd = b$ylen / 2

combinations <- t(combn(1:n, 2))
for (k in 1:nrow(combinations)) {
  j <- combinations[k, 1]
  i <- combinations[k, 2]
  
  
  dx.tmp = abs(b$x[i] - b$x[j]) - b$xd[i] - b$xd[j]
  dy.tmp = abs(b$y[i] - b$y[j]) - b$yd[i] - b$yd[j]
   
  p = 0.5
  if(dx.tmp < 0){
    if(abs(dx.tmp) > p * b$xlen[i]) dx.tmp = Inf
    if(abs(dx.tmp) > p * b$xlen[j]) dx.tmp = Inf
  }
  
  if(dy.tmp < 0){
    if(abs(dy.tmp) > p * b$ylen[i]) dy.tmp = Inf
    if(abs(dy.tmp) > p * b$ylen[j]) dy.tmp = Inf
  }
  
  dx[i, j] <- dx[j, i] <- dx.tmp
  dy[i, j] <- dy[j, i] <- dy.tmp
 
}

d = dx + dy
d[d < 0] = 0
d[d == 0] = 1


```




```{r}


# Пример матрицы весов рёбер
weights_matrix <- d

# Преобразование матрицы в граф
graph <- graph_from_adjacency_matrix(weights_matrix, mode = "undirected", weighted = TRUE)

# Поиск кратчайшего пути из вершины 1 в вершину 5
shortest_path <- shortest_paths(graph, from = 1, to = nrow(b), weights = E(graph)$weight)

# Вывод кратчайшего пути
path.v = shortest_path$vpath[[1]]

path_cost <- sum(
  sapply(seq_along(path.v[-length(path.v)]), function(i) {
    # Индексы начальной и конечной вершины текущего ребра
    v1 <- path.v[i]
    v2 <- path.v[i + 1]
    # Стоимость ребра
    weights_matrix[v1, v2]
  })
)

plotSynDot(b[path.v,])

plotSynDot(b) 
```


```{r}
b.tmp = b[(b$V2 >=10^4) & (b$V2 <=2 * 10^4) & (b$V4 <= 2.5 * 10^4),]
b.tmp$irow = 1:nrow(b.tmp)
plotSynDot(b.tmp)
b = b.tmp


plotSynDot(b)
```




# Algorithm
```{r}
y = x
y = y[y$V4 < y$V5,,drop=F]

```


```{r}
b = y[,2:5]

x.min = min(c(b$V2, b$V3))
x.max = max(c(b$V2, b$V3))
y.min = min(c(b$V4, b$V5))
y.max = max(c(b$V4, b$V5))

b = rbind(c(x.min, x.min, y.min, y.min),
          b,
          c(x.max, x.max, y.max, y.max))


plotSynDot(b)
```














